#!/bin/bash

file= git diff --name-only

echo "$file autoupdated `date +%F-%T`"


DBUSER=gituser

DBPASS=Gitpassword1!

DBNAME=Testgitdatabase



#time= $(date +"%H:%M:%S")
#conflicts_content = git diff

mysql --user=$DB_USER --password=$DB_PASSWD $DB_NAME <<EOF
INSERT INTO conflicts(id, filename, conflict_content, time) VALUES (1, $file, "testcontent", now());
EOF

#git add .
#git commit -a -m "$file autoupdated `date +%F-%T`"
#git push origin main

